apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: kusk-gateway-app
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/aabedraba/swaggerhub-kusk-argocd.git
   targetRevision: HEAD
   path: api
   plugin:
     name: kusk-gateway
 destination:
   server: https://kubernetes.default.svc
   namespace: default