openapi: 3.0.0
info:
  title: Todo-Backend API
  version: 0.0.2
x-kusk:
  cors:
    origins:
      - '*'
    methods:
      - POST
      - GET
    headers:
      - Content-Type
    credentials: true
    max_age: 86200
  upstream:
    service:
      namespace: default
      name: todo-backend
      port: 3000
  path:
    prefix: /
paths:
  /todos:
    get:
      responses:
        '200':
          description: The full list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: Description of what to do
                    completed:
                      type: boolean
                    order:
                      type: integer
                      format: int32
                    url:
                      type: string
                  required:
                    - title
                    - completed
                    - order
                    - url
      summary: Lists all Todos
      description: The returned Todos are ordered by 'order' and then 'title'
      tags:
        - Todo
    post:
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Description of what to do
                  completed:
                    type: boolean
                  order:
                    type: integer
                    format: int32
                  url:
                    type: string
                required:
                  - title
                  - completed
                  - order
                  - url
      summary: Creates a new, uncompleted Todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Description of what to do
                order:
                  type: integer
                  format: int32
              required:
                - title
      tags:
        - Todo